#!/usr/bin/env python3

#from webdriverdownloader import GeckoDriverDownloader
#gdd = GeckoDriverDownloader()
# Currently broken... eg https://github.com/ouseful-template-repos/binder-selenium-demoscraper/issues/1
#gdd.download_and_install()
